### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by alexgleason** [palfrey/wharf#8]
I'd be interested to see what this looks like, maybe with screenshots added to the blog post or README.

**Comment by phasath** [comment]
Please, add it!

**Comment by palfrey** [comment]
Pull requests welcomed for this!

**Comment by arnogues** [comment]
It looks like very very simple, like ugly

**Comment by nbpalomino** [comment]
+1

**Comment by ALenfant** [comment]
Also interested by screenshots, I think it would really help sell this project which sounds really promising!

**Comment by palfrey** [comment]
I'd been really hoping for a user contribution on this (hence the "good first issue" tag), but it looks like I'm not going to get that, so I've done it in 0e82403fcda715dfdefc116fc7919758c8804919. If you don't like the screenshots, please take your own and submit a PR.

**Comment by ALenfant** [comment]
Hey @palfrey 
I understand this is frustrating for you to have to do this but I think it's a bit of a circular issue (no screenshots, less people interested, less contributors able to tackle the issue themselves).
In any case, I wanted to thank you since they're really helpful and sell you project really well!

Thanks for all your work, it seems I'll install it on my instance :)
